export const feedbackActions = {
    SET_CURRENT_EMPLOYEE_FEEDBACK: 'SET_CURRENT_EMPLOYEE_FEEDBACK', 
    SET_ALL_FEEDBACK_FOR_CURRENT_MANAGER: 'SET_ALL_FEEDBACK_FOR_CURRENT_MANAGER',
    SET_ALL_MANAGERS_FEEDBACK_FOR_CURRENT_SUPERVISOR: 'SET_ALL_MANAGERS_FEEDBACK_FOR_CURRENT_SUPERVISOR',
    SET_EMPLOYEE_FOLLOWUP_RECORDS: 'SET_EMPLOYEE_FOLLOWUP_RECORDS',
    SET_ALL_FOLLOWUP_RECORDS: 'SET_ALL_FOLLOWUP_RECORDS'
};