export const FEEDBACK_ACTIONS = {
    SET_CURRENT_EMPLOYEE_FEEDBACK: 'SET_CURRENT_EMPLOYEE_FEEDBACK', 
    SET_ALL_FEEDBACK_FOR_CURRENT_MANAGER: 'SET_ALL_FEEDBACK_FOR_CURRENT_MANAGER',
    SET_ALL_MANAGERS_FEEDBACK_FOR_CURRENT_SUPERVISOR: 'SET_ALL_MANAGERS_FEEDBACK_FOR_CURRENT_SUPERVISOR',
    FETCH_CURRENT_EMPLOYEE_FEEDBACK: 'FETCH_CURRENT_EMPLOYEE_FEEDBACK',
    FETCH_ALL_FEEDBACK_FOR_CURRENT_MANAGER: 'FETCH_ALL_FEEDBACK_FOR_CURRENT_MANAGER',
    FETCH_ALL_FEEDBACK_FOR_CURRENT_SUPERVISOR: 'FETCH_ALL_FEEDBACK_FOR_CURRENT_SUPERVISOR',
    ADD_FEEDBACK: 'ADD_FEEDBACK',
    UPDATE_FEEDBACK: 'UPDATE_FEEDBACK'
};