export const FEEDBACK_ACTIONS = {
  FETCH_CURRENT_EMPLOYEE_FEEDBACK: 'FETCH_CURRENT_EMPLOYEE_FEEDBACK',
  FETCH_ALL_FEEDBACK_BY_CURRENT_SUPERVISOR: 'FETCH_ALL_FEEDBACK_BY_CURRENT_SUPERVISOR',
  FETCH_ALL_FEEDBACK_BY_MANAGER_SUPERVISORS: 'FETCH_ALL_FEEDBACK_BY_MANAGER_SUPERVISORS',
  ADD_FEEDBACK: 'ADD_FEEDBACK',
  UPDATE_FEEDBACK: 'UPDATE_FEEDBACK',
  SET_CURRENT_EMPLOYEE_FEEDBACK: 'SET_CURRENT_EMPLOYEE_FEEDBACK',
  SET_ALL_FEEDBACK_BY_CURRENT_SUPERVISOR: 'SET_ALL_FEEDBACK_BY_CURRENT_SUPERVISOR',
  SET_ALL_FEEDBACK_BY_MANAGER_SUPERVISORS: 'SET_ALL_FEEDBACK_BY_MANAGER_SUPERVISORS',
};