export const FOLLOW_UP_ACTIONS = {
  FETCH_ALL_PENDING_FOLLOWUP: 'FETCH_ALL_PENDING_FOLLOWUP',
  FETCH_EMPLOYEE_PENDING_FOLLOWUP: 'FETCH_EMPLOYEE_PENDING_FOLLOWUP',
  ADD_FOLLOWUP: 'ADD_FOLLOWUP',
  COMPLETE_FOLLOWUP: 'COMPLETE_FOLLOWUP',
  SET_ALL_PENDING_FOLLOWUP: 'SET_ALL_PENDING_FOLLOWUP',
  SET_EMPLOYEE_PENDING_FOLLOWUP: 'SET_EMPLOYEE_PENDING_FOLLOWUP',
};