export const PEOPLE_ACTIONS = {
    FETCH_EMPLOYEES: 'FETCH_EMPLOYEES',
    FETCH_ALL_EMPLOYEES: 'FETCH_ALL_EMPLOYEES',
    ADD_EMPLOYEE: 'ADD_EMPLOYEE',
    DELETE_EMPLOYEE: 'DELETE_EMPLOYEE',
    UPDATE_EMPLOYEE: 'UPDATE_EMPLOYEE',
    FETCH_SUPERVISORS: 'FETCH_SUPERVISORS',
    ADD_SUPERVISOR: 'ADD_SUPERVISOR',
    UPDATE_SUPERVISOR: 'UPDATE_SUPERVISOR',
    DELETE_SUPERVISOR: 'DELETE_SUPERVISOR',
    SET_SUPERVISORS: 'SET_SUPERVISORS',
    SET_SUPERVISOR_EMPLOYEES: 'SET_SUPERVISOR_EMPLOYEES',
    SET_ALL_EMPLOYEES: 'SET_ALL_EMPLOYEES',
}