export const PEOPLE_ACTIONS = {
    SET_MANAGERS: 'SET_MANAGERS',
    SET_MANAGER_EMPLOYEES: 'SET_MANAGER_EMPLOYEES',
    SET_ALL_EMPLOYEES: 'SET_ALL_EMPLOYEES',
    ADD_EMPLOYEE: 'ADD_EMPLOYEE',
    DELETE_EMPLOYEE: 'DELETE_EMPLOYEE',
    UPDATE_EMPLOYEE: 'UPDATE_EMPLOYEE',
    FETCH_EMPLOYEES: 'FETCH_EMPLOYEES',
    FETCH_ALL_EMPLOYEES: 'FETCH_ALL_EMPLOYEES',
}